name: Testing

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver
    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Execute tests
      run: php artisan dusk
